defaults:
  - training: defaults
  - model: defaults
  - dataset: cremma
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: arras

dataset:
  cremma:
    supervised: True
    starts_with: 'Arras-861'

model:
  encoder:
    H: 64

  background:
    init:
      constant: [0.7372549019607844, 0.7254901960784313, 0.6588235294117647]

  loss:
    ctc_factor: 0.1

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-3
