defaults:
  - training: defaults
  - model: defaults
  - dataset: cremma_masks
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: arras

dataset:
  cremma_masks:
    supervised: True
    starts_with: 'Arras-861'

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.5, 0.5, 0.5] 
      #[0.7372549019607844, 0.7254901960784313, 0.6588235294117647]

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  #max_iteration: 637000
  optimizer:
    lr: 1.0e-4

  log:
    milestone: 1


#python train.py arras.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.1 tag=arras-mask-0.1-3