defaults:
  - training: defaults
  - model: defaults
  - dataset: south_north_textualis
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: it783

dataset:
  south_north_textualis:
    supervised: True
    starts_with: 'btv1b8433319z'

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.50, 0.50, 0.50] 
      #[0.7372549019607844, 0.7254901960784313, 0.6588235294117647]

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-4

#python train.py It590.yaml training.optimizer.lr=1.0e-4 model.loss.ctc_factor=0.01 tag=it590-0.01-4