defaults:
  - training: defaults
  - model: defaults
  - dataset: iwcp_south_north
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: iwcp-south-north
dataset:
  iwcp_south_north:
    supervised: True

model:
  encoder:
    H: 96

  background:

    init:
      constant: [0.5, 0.5, 0.5]    

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 300
  optimizer:
    lr: 1.0e-4
  
  log_every: 
    milestone: 1

# python train.py iwcp_south_north.yaml training.optimizer.lr=1.0e-4 model.loss.ctc_factor=0.01 tag=iwcp-south-north-0.01-4