defaults:
  - training: defaults
  - model: defaults
  - dataset: iwcp_caroline
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: iwcp-caroline
dataset:
  iwcp_caroline:
    supervised: True

model:
  encoder:
    H: 96

  background:

    init:
      constant: [0.5, 0.5, 0.5]    
      #[0.6392156862745098, 0.6, 0.5019607843137255]

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 400
  optimizer:
    lr: 1.0e-4
  
  log_every: 
    milestone: 1

# python train.py iwcp_caroline.yaml training.optimizer.lr=1.0e-4 model.loss.ctc_factor=0.01 tag=iwcp-caroline-0.01-4