defaults:
  - training: defaults
  - model: defaults
  - dataset: Lat7499
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: lat7499

dataset:
  Lat7499:
    supervised: True

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.50, 0.50, 0.50] 

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 200
  optimizer:
    lr: 1.0e-4

#python train.py Lat7499.yaml training.optimizer.lr=1.0e-4 model.loss.ctc_factor=0.01 tag=Lat7499-0.01-4