defaults:
  - training: defaults
  - model: defaults
  - dataset: textualis_formata
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: naf4515-16

dataset:
  textualis_formata:
    supervised: True
    starts_with: 'btv1b8455788r'

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.50, 0.50, 0.50] 

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 10000
  optimizer:
    lr: 1.0e-4

#python train.py NAF4515-16.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.1 tag=NAF4515-16-0.1-3
