defaults:
  - training: defaults
  - model: defaults
  - dataset: cremma
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: sbb-sup

dataset:
  cremma:
    supervised: True
    starts_with: 'SBB-PK'

model:
  encoder:
    H: 64

  background:
    init:
      constant: [0.6392156862745098, 0.6, 0.5019607843137255]

  loss:
    ctc_factor: 0.1

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-3

# python train.py sbb-pk.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.1 tag=sbb-sup-0.1