defaults:
  - training: defaults
  - model: defaults
  - dataset: south_north_textualis_mask
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: south_north_textualis_mask

dataset:
  south_north_textualis_mask:
    supervised: True

model:
  encoder:
    H: 96

  background:

    init:
      constant: [0.5, 0.5, 0.5]    
      #[0.6392156862745098, 0.6, 0.5019607843137255]

  loss:
    ctc_factor: 0.1

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 600
  optimizer:
    lr: 1.0e-3
  
  log_every: 
    milestone: 1

# python train.py south_north_textualis_mask.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.1 tag=south_north_textualis_mask_clamp-0.1-3