defaults:
  - training: defaults
  - model: defaults
  - dataset: south_north_textualis
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: sp65

dataset:
  south_north_textualis:
    supervised: True
    starts_with: 'btv1b100361755'

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.50, 0.50, 0.50] 

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-4

#python train.py Sp65.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.01 tag=sp65-0.01-3