defaults:
  - training: defaults
  - model: defaults
  - dataset: textualis_formata_clean
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: textualis_formata_clean

dataset:
  textualis_formata_clean:
    supervised: True
    #exclude: 'btv1b8449715t'

model:
  encoder:
    H: 96 

  sprites:
    size:
      - ${eval:${model.encoder.H}*3//4}
      - ${eval:${model.encoder.H}*3//4}

  transformation:
    canvas_size:
      - ${model.encoder.H}
      - ${eval:${model.encoder.H}*2}

  background:

    init:
      constant: [0.5, 0.5, 0.5]    
      #[0.6392156862745098, 0.6, 0.5019607843137255]

  loss:
    ctc_factor: 0.01

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-4

# python train.py textualis_formata_clean.yaml training.optimizer.lr=1.0e-4 model.loss.ctc_factor=0.01 tag=cipl-textualis_formata_clean-0.01-4