defaults:
  - training: defaults
  - model: defaults
  - dataset: cremma
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  verbose: False

tag: wett

dataset:
  cremma:
    supervised: True
    starts_with: 'Wett'

model:
  encoder:
    H: 96

  background:
    init:
      constant: [0.8862745098039216, 0.8745098039215686, 0.8549019607843137]

  loss:
    ctc_factor: 0.1

training:
  n_workers: 8
  batch_size: 16
  num_epochs: 500
  optimizer:
    lr: 1.0e-3

# python train.py wett.yaml training.optimizer.lr=1.0e-3 model.loss.ctc_factor=0.1 tag=wett-0.1